config/routes.rb
Rails.application.routes.draw do
  root "purchases#index"

  resources :purchases
  resources :summaries, only: [:index, :create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  has_many :user_purchases, dependent: :destroy
  has_many :users, through: :user_purchases

  scope :recent, ->{order date: :desc, created_at: :desc}
  scope :in_month, ->month do
    date = month ? "01/#{month}".to_date : Time.zone.today
    where "date >= ? AND date <= ?", date.beginning_of_month, date.end_of_month
  end
  scope :after_last_summary, -> {
    last_summary = Summary.last
    return unless last_summary
    where("created_at > ?", last_summary.created_at)
  }

  after_save :update_user_purchase_amount

  private

  def update_user_purchase_amount
    user_purchases.update_all amount: (amount / user_purchases.size)
  end
end

app/models/summary.rb
class Summary < ApplicationRecord
  has_many :summary_details, dependent: :destroy

  enum status: [:not_completed, :completed]

  scope :recent, ->{order created_at: :desc}
end

app/models/summary_detail.rb
class SummaryDetail < ApplicationRecord
  belongs_to :user
  belongs_to :summary
end

app/models/user.rb
class User < ApplicationRecord
  has_many :purchases, dependent: :destroy
  has_many :user_purchases, dependent: :destroy

  def amount_purchased_in_month month
    purchases.in_month(month).sum(:amount)
  end

  def all_amount_in_month month
    user_purchases.in_month(month).sum(:amount)
  end
end

app/models/user_purchase.rb
class UserPurchase < ApplicationRecord
  belongs_to :user
  belongs_to :purchase

  scope :in_month, ->(month) {
    where(purchase_id: Purchase.in_month(month).select(:id))
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :load_last_summary, only: [:index, :edit, :update, :destroy]
  before_action :find_purchase, only: [:edit, :update, :destroy]
  before_action :load_users, only: [:new, :edit]

  def index
    @purchases = Purchase.includes(:user).recent.in_month params[:month]
    @total_amount = @purchases.reduce(0){|sum, item| sum + item.amount}
    @users = User.all
  end

  def new
    @purchase = Purchase.new
    @purchase.user_ids = @users.map(&:second)
  end

  def create
    @purchase = Purchase.new purchase_params

    if @purchase.save
      flash[:success] = "Thêm mới thành công"
      redirect_to purchases_path
    else
      flash.now[:warning] = "Không thể thêm mới"
      load_users
      render :new
    end
  end

  def edit
  end

  def update
    if @purchase.update_attributes purchase_params
      flash[:success] = "Cập nhật thành công"
      redirect_to purchases_path
    else
      flash.now[:warning] = "Không thể cập nhật"
      load_users
      render :edit
    end
  end

  def destroy
    if @purchase.destroy
      flash[:success] = "Xóa thành công"
    else
      flash[:warning] = "Không thể xóa"
    end
    redirect_to purchases_path
  end

  private

  def purchase_params
    params.require(:purchase).permit :user_id, :date, :amount, :note, user_ids: []
  end

  def find_purchase
    @purchase = Purchase.find_by id: params[:id]

    return if @purchase
    flash[:warning] = "Không tìm thấy khoản chi"
    redirect_to root_path
    return if !@summary || @purchase.created_at > @summary.created_at
    flash[:warning] = "Không thực hiện được thao tác này"
    redirect_to root_path
  end

  def load_users
    @users = User.pluck :name, :id
  end

  def load_last_summary
    @summary = Summary.last
  end
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  before_action :find_summary, only: [:update, :destroy]

  def index
    @summaries = Summary.includes(summary_details: :user).recent
  end

  def create
    created, msg = SummaryServices::CreateSummary.new.perform

    if created
      flash[:success] = "Thêm mới thành công"
    else
      flash[:warning] = msg || "Không thể thêm mới"
    end
    redirect_to summaries_path
  end

  def update
    if @summary.completed!
      flash[:success] = "Cập nhật thành công"
    else
      flash[:warning] = "Không thể cập nhật"
    end
    redirect_to summaries_path
  end

  def destroy
    if @summary.not_completed? && @summary.destroy
      flash[:success] = "Xóa thành công"
    else
      flash[:warning] = "Không thể xóa"
    end
    redirect_to summaries_path
  end

  private

  def find_summary
    @summary = Summary.find_by id: params[:id]

    return if @summary
    flash[:warning] = "Không tìm thấy bản ghi"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "202", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Danh sách khoản mua", purchases_path %>
        </li>
        <li>
          <%= link_to "Danh sách tổng tiền", summaries_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>202</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div class="wrapper">
      <header>
        <%= render "layouts/navbar" %>
      </header>
      <div class="container">
        <div class="flash-errors">
          <% flash.each do |message_type, message| %>
            <div class="autohide alert alert-<%= message_type %>">
              <%= message.html_safe %>
            </div>
          <% end %>
        </div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/purchases/_form.html.erb
<%= form_for purchase do |f| %>
  <div class="form-group">
    <%= f.label "Người mua" %>
    <%= f.select :user_id, users, {include_blank: "Chọn người mua"},
      class: "form-control select2", required: true %>
  </div>
  <div class="form-group">
    <%= f.label "Ngày mua" %>
    <%= f.text_field :date, value: f.object.date || Time.zone.today,
      class: "form-control date-picker", required: true, autocomplete: :off %>
  </div>
  <div class="form-group">
    <%= f.label "Số tiền" %>
    <div class="input-group">
      <%= f.number_field :amount, class: "form-control", step: 1, min: 0,
        required: true, autocomplete: :off %>
      <span class="input-group-addon">VNĐ</span>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Nội dung" %>
    <%= f.text_area :note, class: "form-control", required: true, autocomplete: :off %>
  </div>
  <div class="form-group">
    <%= f.label "Chia cho" %>
    <%= f.select :user_ids, users, {include_blank: "Chia cho"},
      class: "form-control select2", required: true, multiple: true %>
  </div>
  <div class="text-right">
    <%= f.button type: :submit, class: "btn btn-primary" do %>
      <i class="fa fa-floppy-o"></i> Lưu lại
    <% end %>
  </div>
<% end %>

app/views/purchases/_purchase.html.erb
<tr>
  <td class="text-right"><%= purchase_counter + 1 %></td>
  <td><%= purchase.user.name %></td>
  <td class="text-center"><%= l purchase.date %></td>
  <td class="text-right"><%= number_to_currency purchase.amount %></td>
  <td><%= purchase.note %></td>
  <td><%= purchase.users.pluck(:name).join(", ") %></td>
  <td class="text-center">
    <% if !@summary || purchase.created_at > @summary.created_at %>
      <%= link_to edit_purchase_path(purchase),
        class: "btn btn-info btn-xs" do %>
        <i class="fa fa-pencil"></i> Sửa
      <% end %>
      <%= link_to purchase_path(purchase), class: "btn btn-danger btn-xs",
        data: {confirm: "Xác nhận xóa?"}, method: :delete do %>
        <i class="fa fa-trash"></i> Xóa
      <% end %>
    <% end %>
  </td>
</tr>

app/views/purchases/edit.html.erb
<h1 class="page-title">Cập nhật khoản mua</h1>

<div class="row">
  <div class="col-md-12">
    <%= render "form", purchase: @purchase, users: @users %>
  </div>
</div>

app/views/purchases/index.html.erb
<h1 class="page-title">Danh sách khoản mua</h1>

<div class="row">
  <div class="col-md-12">
    <%= form_tag purchases_path, method: :get do %>
      <div class="form-group">
        <div class="form-inline">
          <div class="input-group">
            <%= text_field_tag :month,
              params[:month] || Time.zone.today.strftime("%m/%Y"),
              class: "form-control month-picker submit-on-change",
              placeholder: "Chọn tháng", autocomplete: :off %>
            <span class="input-group-btn">
              <%= button_tag name: "", class: "btn btn-default" do %>
                <i class="fa fa-search"></i>
              <% end %>
            </span>
          </div>
          <%= link_to new_purchase_path,
            class: "btn btn-primary pull-right" do %>
            <i class="fa fa-plus"></i> Thêm mới
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-12">
    <div class="content">
      <table class="table table-hovered table-striped table-bordered">
        <thead>
          <tr>
            <th class="text-center">#</th>
            <th class="text-center">Người mua</th>
            <th class="text-center">Ngày mua</th>
            <th class="text-center">Số tiền</th>
            <th class="text-center">Nội dung</th>
            <th class="text-center">Chia cho</th>
            <th class="text-center">Thao tác</th>
          </tr>
        </thead>
        <tbody>
          <% if @purchases.any? %>
            <%= render @purchases %>
          <% else %>
            <tr>
              <td colspan="7">Chưa có khoản mua nào</td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr class="text-bold">
            <td colspan="3" class="text-right">Tổng:</td>
            <td class="text-right"><%= number_to_currency @total_amount %></td>
            <td colspan="3"></td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
  <div class="col-md-12">
    <table class="table table-hovered table-bordered table-striped">
      <thead>
        <tr>
          <th class="text-center">#</th>
          <th class="text-center"></th>
          <th class="text-center">Tiền chi</th>
          <th class="text-center">Tiền tiêu</th>
          <th class="text-center">Còn dư</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each.with_index 1 do |user, index| %>
          <tr>
            <td class="text-right"><%= index %></td>
            <td><%= user.name %></td>
            <td class="text-right text-bold">
              <%= number_to_currency(x = user.amount_purchased_in_month(params[:month])) %>
            </td>
            <td class="text-right text-bold">
              <%= number_to_currency(y = user.all_amount_in_month(params[:month])) %>
            </td>
            <td class="text-right text-bold">
              <%= number_to_currency(x - y) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/purchases/new.html.erb
<h1 class="page-title">Thêm mới khoản mua</h1>

<div class="row">
  <div class="col-md-12">
    <%= render "form", purchase: @purchase, users: @users %>
  </div>
</div>

app/views/summaries/_summary.html.erb
<tr>
  <td class="text-right"><%= summary_counter + 1 %></td>
  <td class="text-center"><%= l summary.created_at %></td>
  <td>
    <% summary.summary_details.each do |detail| %>
      <%= "#{detail.user.name}: <b>#{number_to_currency detail.amount}</b>".html_safe %>
      <hr>
    <% end %>
  </td>
  <td><%= t "summary.statuses.#{summary.status}" %></td>
  <td class="text-center">
    <% if summary.not_completed? %>
      <%= link_to summary_path(summary), class: "btn btn-info btn-xs",
        data: {confirm: "Xác nhận cập nhật?"}, method: :patch do %>
        <i class="fa fa-check-square-o"></i> Đã hoàn tất
      <% end %>
      <%= link_to summary_path(summary), class: "btn btn-danger btn-xs",
        data: {confirm: "Xác nhận xóa?"}, method: :delete do %>
        <i class="fa fa-trash"></i> Xóa
      <% end %>
    <% end %>
  </td>
</tr>

app/views/summaries/index.html.erb
<h1 class="page-title">Danh sách tổng tiền</h1>

<div class="row">
  <div class="col-md-12">
    <%= form_tag summaries_path, method: :post do %>
      <div class="form-group">
        <div class="form-inline">
          <%= button_tag type: :submit, class: "btn btn-primary pull-right" do %>
            <i class="fa fa-plus"></i> Thêm mới
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-12">
    <div class="content">
      <table class="table table-hovered table-striped table-bordered">
        <thead>
          <tr>
            <th class="text-center">#</th>
            <th class="text-center">Thời gian tạo</th>
            <th class="text-center">Chi tiết</th>
            <th class="text-center">Trạng thái</th>
            <th class="text-center">Thao tác</th>
          </tr>
        </thead>
        <tbody>
          <% if @summaries.any? %>
            <%= render @summaries %>
          <% else %>
            <tr>
              <td colspan="5">Chưa có chi tiết tổng tiền nào</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>